server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002
  client:
    register-with-eureka: false #表示是否像erueka注册中心注册自己
    fetch-registry: false  #表示自己为注册中心
    service-url: #监控页面
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7003:7003/eureka/
