server:
  port: 9527

spring:
  application:
    name: springcloud-zuul

#eureka 的配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
  instance:
    instance-id: springcloud-zuul-9527
    prefer-ip-address: true  #隐藏ip

#info配置
info:
  app.name: springcloud-zuul-9527

zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
  ignored-services: springcloud-provider-dept